export const image_city =require('../src/images/city.png')
export const image_state =require('../src/images/state.png')
export const image_pincode =require('../src/images/pincode.png')
export const image_radio_unselected =require('../src/images/radio.png')
export const image_radio_selected =require('../src/images/radio_selected.png')
export const image_back =require('../src/images/left.png')
